name: builds
on:
  push:
    branches:
      - master
  pull_request:

env:
  VERBOSE: 1
  INSTALL_PATH: build
jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 gfortran mpich libomp-dev
      - uses: actions/checkout@v2
        with:
          repository: anlsys/libnrm
          path: libnrm
      - name: configure
        run: |
          cd libnrm
          ./autogen.sh
          ./configure --prefix=$GITHUB_WORKSPACE/$INSTALL_PATH
          make
          make install
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: nrm-extra
      - name: configure
        run: |
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib/pkgconfig:$PKG_CONFIG_PATH
          cd nrm-extra
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build CC=clang-12
      - name: make
        run: |
          cd nrm-extra
          make
      - name: make check
        run: |
          cd nrm-extra
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib:$LD_LIBRARY_PATH
          make check
          make install
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: generic
          path: |
            nrm-extra/config.log
            nrm-extra/ctests/*.log
            nrm-extra/ftests/*.log
  out-of-tree:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 gfortran mpich libomp-dev
      - uses: actions/checkout@v2
        with:
          repository: anlsys/libnrm
          path: libnrm
      - name: configure
        run: |
          cd libnrm
          ./autogen.sh
          ./configure --prefix=$GITHUB_WORKSPACE/$INSTALL_PATH
          make
          make install
      - uses: actions/checkout@v2
        with:
          path: nrm-extra
      - name: configure
        run: |
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib/pkgconfig:$PKG_CONFIG_PATH
          cd nrm-extra
          ./autogen.sh
          mkdir out
          cd out
          mkdir build
          ../configure --prefix=`pwd`/build CC=clang-12
      - name: make
        run: |
          cd nrm-extra/out
          make
      - name: make check
        run: |
          cd nrm-extra/out
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib:$LD_LIBRARY_PATH
          make check
          make install
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: out-of-tree
          path: |
            nrm-extra/out/config.log
            nrm-extra/out/ctests/*.log
            nrm-extra/out/ftests/*.log
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - run: nix-build -A nrm-extra
  distcheck:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 gfortran mpich libomp-dev
      - uses: actions/checkout@v2
        with:
          repository: anlsys/libnrm
          path: libnrm
      - name: configure
        run: |
          cd libnrm
          ./autogen.sh
          ./configure --prefix=$GITHUB_WORKSPACE/$INSTALL_PATH
          make
          make install
      - uses: actions/checkout@v2
        with:
          path: nrm-extra
      - name: configure
        run: |
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib/pkgconfig:$PKG_CONFIG_PATH
          cd nrm-extra
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build CC=clang-12
      - name: make distcheck
        run: |
          cd nrm-extra
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$INSTALL_PATH/lib:$LD_LIBRARY_PATH
          make distcheck
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: distcheck
          path: |
            nrm-extra/config.log
            nrm-extra/ctests/*.log
            nrm-extra/ftests/*.log
